# Generated by Django 3.2.3 on 2024-04-27 16:50

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_prevista', models.DateTimeField()),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.CharField(blank=True, max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name='Alarma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_alarma', models.CharField(choices=[('Abierta', 'Abierta'), ('Cerrada', 'Cerrada')], default='Abierta', max_length=20)),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('observaciones', models.CharField(blank=True, max_length=10000)),
                ('resumen', models.CharField(blank=True, max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Clasificacion_Alarma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('codigo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Clasificacion_Recurso_Comunitario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Convocatoria_Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('convocatoria', models.CharField(blank=True, max_length=1000)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameDescritive', models.CharField(max_length=200)),
                ('engine', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('user', models.CharField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(blank=True, max_length=200, null=True)),
                ('host', models.CharField(blank=True, max_length=200, null=True)),
                ('port', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Desarrollador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=1000)),
                ('descripcion', models.CharField(blank=True, max_length=10000)),
                ('imagen', models.ImageField(blank=True, default='', null=True, upload_to='desarrollador/imagen_desarrollador')),
                ('es_profesor', models.BooleanField(default=False)),
                ('id_convocatoria_proyecto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='desarrolladores', to='teleasistenciaApp.convocatoria_proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localidad', models.CharField(max_length=200)),
                ('provincia', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=200)),
                ('codigo_postal', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Gestion_Base_Datos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubicacion_copia', models.CharField(default='/Server/teleasistencia/backup', max_length=200)),
                ('fecha_copia', models.DateField(default=django.utils.timezone.now)),
                ('descripcion_copia', models.CharField(default='Copia sin descripcion.', max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Logs_ConexionesUsuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('direccion_ip', models.CharField(max_length=40)),
                ('username', models.CharField(max_length=150)),
                ('login_correcto', models.BooleanField(default=False)),
                ('tipo_login', models.CharField(choices=[('PANEL_ADMIN', 'PANEL_ADMIN'), ('TOKEN_API', 'TOKEN_API'), ('OTRO', 'OTRO')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiene_ucr', models.BooleanField(default=False)),
                ('numero_expediente', models.CharField(blank=True, max_length=200)),
                ('numero_seguridad_social', models.CharField(max_length=200)),
                ('prestacion_otros_servicios_sociales', models.CharField(blank=True, max_length=2000)),
                ('observaciones_medicas', models.CharField(blank=True, max_length=6000)),
                ('intereses_y_actividades', models.CharField(blank=True, max_length=6000)),
            ],
        ),
        migrations.CreateModel(
            name='Recurso_Comunitario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=500)),
                ('telefono', models.CharField(max_length=20)),
                ('id_direccion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teleasistenciaApp.direccion')),
            ],
        ),
        migrations.CreateModel(
            name='Tecnologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=1000)),
                ('imagen', models.ImageField(blank=True, default='', null=True, upload_to='desarrollador/imagen_tecnologia')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('codigo', models.CharField(max_length=100)),
                ('importancia', models.CharField(choices=[('Alta', 'Alta'), ('Baja', 'Baja')], default='Baja', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Modalidad_Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Situacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Vivienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Recurso_Comunitario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('id_clasificacion_recurso_comunitario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teleasistenciaApp.clasificacion_recurso_comunitario')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Alarma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('codigo', models.CharField(max_length=200)),
                ('es_dispositivo', models.BooleanField(default=True)),
                ('id_clasificacion_alarma', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teleasistenciaApp.clasificacion_alarma')),
            ],
        ),
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_terminal', models.CharField(max_length=30)),
                ('modo_acceso_vivienda', models.CharField(max_length=400)),
                ('barreras_arquitectonicas', models.CharField(blank=True, max_length=5000)),
                ('modelo_terminal', models.CharField(blank=True, max_length=400)),
                ('fecha_tipo_situacion', models.DateField(default=django.utils.timezone.now, null=True)),
                ('id_tipo_situacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teleasistenciaApp.tipo_situacion')),
                ('id_tipo_vivienda', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teleasistenciaApp.tipo_vivienda')),
                ('id_titular', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='teleasistenciaApp.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Relacion_Terminal_Recurso_Comunitario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiempo_estimado', models.IntegerField(default=1)),
                ('id_recurso_comunitario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teleasistenciaApp.recurso_comunitario')),
                ('id_terminal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teleasistenciaApp.terminal')),
            ],
        ),
        migrations.CreateModel(
            name='Relacion_Paciente_Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('apellidos', models.CharField(max_length=200)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('tipo_relacion', models.CharField(max_length=200)),
                ('tiene_llaves_vivienda', models.BooleanField(blank=True, default=False)),
                ('disponibilidad', models.CharField(blank=True, max_length=200)),
                ('observaciones', models.CharField(blank=True, max_length=4000)),
                ('prioridad', models.IntegerField(blank=True)),
                ('es_conviviente', models.BooleanField(default=False)),
                ('tiempo_domicilio', models.IntegerField(default=1)),
                ('id_paciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teleasistenciaApp.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Recursos_Comunitarios_En_Alarma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('id_alarma', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teleasistenciaApp.alarma')),
                ('id_recurso_comunitario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teleasistenciaApp.recurso_comunitario')),
            ],
        ),
        migrations.AddField(
            model_name='recurso_comunitario',
            name='id_tipos_recurso_comunitario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teleasistenciaApp.tipo_recurso_comunitario'),
        ),
        migrations.CreateModel(
            name='Persona_Contacto_En_Alarma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('id_alarma', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teleasistenciaApp.alarma')),
                ('id_persona_contacto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teleasistenciaApp.relacion_paciente_persona')),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('apellidos', models.CharField(max_length=200)),
                ('dni', models.CharField(max_length=20)),
                ('fecha_nacimiento', models.DateField(blank=True)),
                ('sexo', models.CharField(choices=[('Hombre', 'Hombre'), ('Mujer', 'Mujer')], default='Hombre', max_length=20)),
                ('telefono_fijo', models.CharField(blank=True, max_length=20)),
                ('telefono_movil', models.CharField(blank=True, max_length=20)),
                ('id_direccion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teleasistenciaApp.direccion')),
            ],
        ),
        migrations.AddField(
            model_name='paciente',
            name='id_persona',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teleasistenciaApp.persona'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='id_terminal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teleasistenciaApp.terminal'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='id_tipo_modalidad_paciente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teleasistenciaApp.tipo_modalidad_paciente'),
        ),
        migrations.CreateModel(
            name='Logs_AccionesUsuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('direccion_ip', models.CharField(max_length=40)),
                ('ruta', models.TextField(default='')),
                ('query', models.TextField(default='')),
                ('metodo_http', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE')], max_length=6)),
                ('estado_http', models.CharField(max_length=10)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Imagen_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, default='', null=True, upload_to='imagen_usuario')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Historico_Agenda_Llamadas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observaciones', models.CharField(blank=True, max_length=4000)),
                ('id_agenda', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historico_agenda', to='teleasistenciaApp.agenda')),
                ('id_teleoperador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Dispositivos_Auxiliares_En_Terminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_terminal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teleasistenciaApp.terminal')),
                ('id_tipo_alarma', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teleasistenciaApp.tipo_alarma')),
            ],
        ),
        migrations.CreateModel(
            name='Desarrollador_Tecnologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_desarrollador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='desarrollador_tecnologias', to='teleasistenciaApp.desarrollador')),
                ('id_tecnologia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teleasistenciaApp.tecnologia')),
            ],
        ),
        migrations.CreateModel(
            name='Database_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('database', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teleasistenciaApp.database')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Alarma_Programada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('id_paciente_ucr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teleasistenciaApp.paciente')),
                ('id_terminal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teleasistenciaApp.terminal')),
                ('id_tipo_alarma', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teleasistenciaApp.tipo_alarma')),
            ],
        ),
        migrations.AddField(
            model_name='alarma',
            name='id_paciente_ucr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teleasistenciaApp.paciente'),
        ),
        migrations.AddField(
            model_name='alarma',
            name='id_teleoperador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alarma',
            name='id_terminal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teleasistenciaApp.terminal'),
        ),
        migrations.AddField(
            model_name='alarma',
            name='id_tipo_alarma',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teleasistenciaApp.tipo_alarma'),
        ),
        migrations.AddField(
            model_name='agenda',
            name='id_paciente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teleasistenciaApp.paciente'),
        ),
        migrations.AddField(
            model_name='agenda',
            name='id_tipo_agenda',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teleasistenciaApp.tipo_agenda'),
        ),
        migrations.AddField(
            model_name='user',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teleasistenciaApp.paciente'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
