# Generated by Django 3.2.3 on 2021-05-19 15:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateField(default=django.utils.timezone.now)),
                ('fecha_prevista', models.DateField()),
                ('fecha_resolucion', models.DateField()),
                ('observaciones', models.CharField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name='Alarma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_alarma', models.CharField(choices=[('Abierta', 'Abierta'), ('Cerrada', 'Cerrada')], default='Abierta', max_length=20)),
                ('fecha_registro', models.DateField(default=django.utils.timezone.now)),
                ('observaciones', models.CharField(max_length=10000)),
                ('resumen', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Centro_Sanitario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localidad', models.CharField(max_length=200)),
                ('provincia', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=200)),
                ('codigo_postal', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiene_ucr', models.BooleanField(default=False)),
                ('numero_expediente', models.CharField(max_length=200)),
                ('numero_seguridad_social', models.CharField(max_length=200)),
                ('prestacion_otros_servicios_sociales', models.CharField(max_length=2000)),
                ('observaciones_medicas', models.CharField(max_length=6000)),
                ('intereses_y_actividades', models.CharField(max_length=6000)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('apellidos', models.CharField(max_length=200)),
                ('dni', models.CharField(max_length=20)),
                ('fecha_nacimiento', models.DateField()),
                ('importancia', models.CharField(choices=[('Hombre', 'Hombre'), ('Mujer', 'Mujer')], default='Hombre', max_length=20)),
                ('telefono_fijo', models.CharField(max_length=20)),
                ('telefono_movil', models.CharField(max_length=20)),
                ('id_direccion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teleasistenciaApp.direccion')),
            ],
        ),
        migrations.CreateModel(
            name='Recurso_Comunitario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=20)),
                ('id_direccion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teleasistenciaApp.direccion')),
            ],
        ),
        migrations.CreateModel(
            name='Subtipo_Alarma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('codigo', models.CharField(max_length=200)),
                ('es_dispositivo', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('codigo', models.IntegerField()),
                ('importancia', models.CharField(choices=[('Urgente', 'Urgente'), ('Importante', 'Importante')], default='Importante', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Centro_Sanitario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Modalidad_Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Recurso_Comunitario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Situacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Vivienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Alarma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('codigo', models.CharField(max_length=200)),
                ('id_subtipo_alarma', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teleasistenciaApp.subtipo_alarma')),
            ],
        ),
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_terminal', models.CharField(max_length=30)),
                ('modo_acceso_vivienda', models.CharField(max_length=400)),
                ('barreras_arquitectonicas', models.CharField(max_length=5000)),
                ('id_tipo_vivienda', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teleasistenciaApp.tipo_vivienda')),
                ('id_titular', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teleasistenciaApp.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Relacion_Terminal_Recurso_Comunitario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_recurso_comunitario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teleasistenciaApp.recurso_comunitario')),
                ('id_terminal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teleasistenciaApp.terminal')),
            ],
        ),
        migrations.CreateModel(
            name='Relacion_Paciente_Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_relacion', models.CharField(max_length=200)),
                ('tiene_llaves_vivienda', models.BooleanField(default=False)),
                ('disponibilidad', models.CharField(max_length=200)),
                ('observaciones', models.CharField(max_length=4000)),
                ('prioridad', models.IntegerField()),
                ('id_paciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teleasistenciaApp.paciente')),
                ('id_persona', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teleasistenciaApp.persona')),
            ],
        ),
        migrations.CreateModel(
            name='Relacion_Paciente_Centro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persona_contacto', models.CharField(max_length=200)),
                ('distancia_km', models.IntegerField()),
                ('tiempo_minutos', models.IntegerField()),
                ('observaciones', models.CharField(max_length=4000)),
                ('id_centro_sanitario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teleasistenciaApp.centro_sanitario')),
                ('id_paciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teleasistenciaApp.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Recursos_Comunitarios_En_Alarma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateField(default=django.utils.timezone.now)),
                ('persona', models.CharField(max_length=1000)),
                ('acuerdo_alcanzado', models.CharField(max_length=5000)),
                ('id_alarma', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teleasistenciaApp.alarma')),
                ('id_recurso_comunitario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teleasistenciaApp.recurso_comunitario')),
            ],
        ),
        migrations.AddField(
            model_name='recurso_comunitario',
            name='id_tipos_recurso_comunitario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teleasistenciaApp.tipo_recurso_comunitario'),
        ),
        migrations.CreateModel(
            name='Persona_Contacto_En_Alarma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateField(default=django.utils.timezone.now)),
                ('acuerdo_alcanzado', models.CharField(max_length=5000)),
                ('id_alarma', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teleasistenciaApp.alarma')),
                ('id_persona_contacto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teleasistenciaApp.persona')),
            ],
        ),
        migrations.AddField(
            model_name='paciente',
            name='id_persona',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teleasistenciaApp.persona'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='id_terminal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teleasistenciaApp.terminal'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='id_tipo_modalidad_paciente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teleasistenciaApp.tipo_modalidad_paciente'),
        ),
        migrations.CreateModel(
            name='Historico_Tipo_Situacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_terminal_alarma', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teleasistenciaApp.terminal')),
                ('id_tipo_situacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teleasistenciaApp.tipo_situacion')),
            ],
        ),
        migrations.CreateModel(
            name='Historico_Terminal_Subtipo_Alarma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_subtipo_alarma', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teleasistenciaApp.subtipo_alarma')),
                ('id_terminal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teleasistenciaApp.terminal')),
            ],
        ),
        migrations.CreateModel(
            name='Historico_Agenda_Llamadas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_llamada', models.DateField(default=django.utils.timezone.now)),
                ('observaciones', models.CharField(max_length=4000)),
                ('id_agenda', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teleasistenciaApp.agenda')),
                ('id_teleoperador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Centro_Sanitario_En_Alarma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateField(default=django.utils.timezone.now)),
                ('persona', models.CharField(max_length=1000)),
                ('acuerdo_alcanzado', models.CharField(max_length=5000)),
                ('id_alarma', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teleasistenciaApp.alarma')),
                ('id_centro_sanitario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teleasistenciaApp.centro_sanitario')),
            ],
        ),
        migrations.AddField(
            model_name='centro_sanitario',
            name='id_direccion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teleasistenciaApp.direccion'),
        ),
        migrations.AddField(
            model_name='centro_sanitario',
            name='id_tipos_centro_sanitario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teleasistenciaApp.tipo_centro_sanitario'),
        ),
        migrations.AddField(
            model_name='alarma',
            name='id_paciente_ucr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teleasistenciaApp.paciente'),
        ),
        migrations.AddField(
            model_name='alarma',
            name='id_teleoperador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alarma',
            name='id_terminal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teleasistenciaApp.terminal'),
        ),
        migrations.AddField(
            model_name='alarma',
            name='id_tipo_alarma',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teleasistenciaApp.tipo_alarma'),
        ),
        migrations.AddField(
            model_name='agenda',
            name='id_paciente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teleasistenciaApp.paciente'),
        ),
        migrations.AddField(
            model_name='agenda',
            name='id_persona',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teleasistenciaApp.persona'),
        ),
        migrations.AddField(
            model_name='agenda',
            name='id_tipo_agenda',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teleasistenciaApp.tipo_agenda'),
        ),
        ]
