# Generated by Django 3.2.3 on 2021-05-27 14:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('teleasistenciaApp', '0004_auto_20210526_1611'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clasificacion_Alarma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('codigo', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameModel(
            old_name='Historico_Terminal_Subtipo_Alarma',
            new_name='Historico_Terminal_Tipo_Alarma',
        ),
        migrations.RemoveField(
            model_name='historico_terminal_tipo_alarma',
            name='id_subtipo_alarma',
        ),
        migrations.AddField(
            model_name='centro_sanitario',
            name='nombre',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='historico_terminal_tipo_alarma',
            name='id_tipo_alarma',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teleasistenciaApp.tipo_alarma'),
        ),
        migrations.AddField(
            model_name='historico_tipo_situacion',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='recurso_comunitario',
            name='nombre',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='tipo_alarma',
            name='es_dispositivo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='persona_contacto_en_alarma',
            name='acuerdo_alcanzado',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='recursos_comunitarios_en_alarma',
            name='persona',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='relacion_paciente_centro',
            name='distancia_km',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='relacion_paciente_centro',
            name='observaciones',
            field=models.CharField(blank=True, max_length=4000),
        ),
        migrations.AlterField(
            model_name='relacion_paciente_centro',
            name='tiempo_minutos',
            field=models.IntegerField(blank=True),
        ),
        migrations.DeleteModel(
            name='Subtipo_Alarma',
        ),
        migrations.AddField(
            model_name='tipo_alarma',
            name='id_clasificacion_alarma',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teleasistenciaApp.clasificacion_alarma'),
        ),
    ]
