# Generated by Django 3.2.3 on 2021-05-31 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teleasistenciaApp', '0005_auto_20210527_1444'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Historico_Terminal_Tipo_Alarma',
            new_name='Dispositivos_Auxiliares_En_Terminal',
        ),
    ]
