# Generated by Django 3.2.3 on 2021-11-22 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teleasistenciaApp', '0007_rename_importancia_persona_sexo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relacion_Usuario_Centro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persona_contacto', models.CharField(blank=True, max_length=1000)),
                ('distancia', models.IntegerField(blank=True)),
                ('tiempo', models.IntegerField(blank=True)),
                ('observaciones', models.CharField(blank=True, max_length=1000)),
                ('id_centro_sanitario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teleasistenciaApp.centro_sanitario')),
                ('id_paciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teleasistenciaApp.paciente')),
            ],
        ),
    ]
