# Generated by Django 3.2.3 on 2022-05-23 09:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('teleasistenciaApp', '0010_auto_20220427_1548'),
    ]

    operations = [
        migrations.CreateModel(
            name='Convocatoria_Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('convocatoria', models.CharField(blank=True, max_length=1000)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Desarrollador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=1000)),
                ('descripcion', models.CharField(blank=True, max_length=10000)),
                ('imagen', models.ImageField(blank=True, default='', null=True, upload_to='desarrollador/imagen_desarrollador')),
                ('es_profesor', models.BooleanField(default=False)),
                ('id_convocatoria_proyecto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teleasistenciaApp.convocatoria_proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='Tecnologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=1000)),
                ('imagen', models.ImageField(blank=True, default='', null=True, upload_to='desarrollador/imagen_tecnologia')),
            ],
        ),
        migrations.CreateModel(
            name='Desarrollador_Tecnologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_desarrollador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teleasistenciaApp.desarrollador')),
                ('id_tecnologia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teleasistenciaApp.tecnologia')),
            ],
        ),
    ]
