# Generated by Django 3.2.3 on 2022-05-27 11:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('teleasistenciaApp', '0012_auto_20220523_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gestion_Base_Datos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubicacion_copia', models.CharField(default='/Server/teleasistencia/backup', max_length=200)),
                ('fecha_copia', models.DateField(default=django.utils.timezone.now)),
                ('descripcion_copia', models.CharField(default='Copia sin descripcion.', max_length=300, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='historico_agenda_llamadas',
            name='id_agenda',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historico_agenda', to='teleasistenciaApp.agenda'),
        ),
    ]
