# Generated by Django 3.2.3 on 2023-02-23 10:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('teleasistenciaApp', '0013_auto_20220527_1357'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clasificacion_Recurso_Comunitario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='centro_sanitario_en_alarma',
            name='id_alarma',
        ),
        migrations.RemoveField(
            model_name='centro_sanitario_en_alarma',
            name='id_centro_sanitario',
        ),
        migrations.RemoveField(
            model_name='relacion_paciente_centro',
            name='id_centro_sanitario',
        ),
        migrations.RemoveField(
            model_name='relacion_paciente_centro',
            name='id_paciente',
        ),
        migrations.RemoveField(
            model_name='relacion_usuario_centro',
            name='id_centro_sanitario',
        ),
        migrations.RemoveField(
            model_name='relacion_usuario_centro',
            name='id_paciente',
        ),
        migrations.RemoveField(
            model_name='historico_agenda_llamadas',
            name='fecha_llamada',
        ),
        migrations.RemoveField(
            model_name='persona_contacto_en_alarma',
            name='acuerdo_alcanzado',
        ),
        migrations.RemoveField(
            model_name='recursos_comunitarios_en_alarma',
            name='acuerdo_alcanzado',
        ),
        migrations.RemoveField(
            model_name='recursos_comunitarios_en_alarma',
            name='persona',
        ),
        migrations.AddField(
            model_name='relacion_paciente_persona',
            name='es_conviviente',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='terminal',
            name='modelo_terminal',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='fecha_prevista',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='fecha_registro',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='fecha_resolucion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='persona_contacto_en_alarma',
            name='fecha_registro',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='recursos_comunitarios_en_alarma',
            name='fecha_registro',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='tipo_agenda',
            name='importancia',
            field=models.CharField(choices=[('Alta', 'Alta'), ('Baja', 'Baja')], default='Baja', max_length=20),
        ),
        migrations.DeleteModel(
            name='Centro_Sanitario',
        ),
        migrations.DeleteModel(
            name='Centro_Sanitario_En_Alarma',
        ),
        migrations.DeleteModel(
            name='Relacion_Paciente_Centro',
        ),
        migrations.DeleteModel(
            name='Relacion_Usuario_Centro',
        ),
        migrations.DeleteModel(
            name='Tipo_Centro_Sanitario',
        ),
        migrations.AddField(
            model_name='tipo_recurso_comunitario',
            name='id_clasificacion_recurso_comunitario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teleasistenciaApp.clasificacion_recurso_comunitario'),
        ),
    ]
