# Generated by Django 3.2.3 on 2023-02-24 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teleasistenciaApp', '0014_auto_20230223_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='relacion_terminal_recurso_comunitario',
            name='tiempo_estimado',
            field=models.IntegerField(default=1),
        ),
    ]
