# Generated by Django 3.2.3 on 2023-03-29 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teleasistenciaApp', '0015_relacion_terminal_recurso_comunitario_tiempo_estimado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipo_agenda',
            name='codigo',
            field=models.CharField(max_length=100),
        ),
    ]
