# Generated by Django 3.2.3 on 2023-04-12 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teleasistenciaApp', '0017_alter_tipo_agenda_codigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenda',
            name='id_persona',
        ),
        migrations.RemoveField(
            model_name='relacion_paciente_persona',
            name='id_persona',
        ),
        migrations.AddField(
            model_name='relacion_paciente_persona',
            name='apellidos',
            field=models.CharField(default='Apellido', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='relacion_paciente_persona',
            name='nombre',
            field=models.CharField(default='Nombre', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='relacion_paciente_persona',
            name='telefono',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
