# Generated by Django 3.2.3 on 2023-04-12 10:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teleasistenciaApp', '0018_auto_20230412_1014'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logs_ConexionesUsuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('direccion_ip', models.CharField(max_length=40)),
                ('username', models.CharField(max_length=150)),
                ('login_correcto', models.BooleanField(default=False)),
                ('tipo_login', models.CharField(choices=[('PANEL_ADMIN', 'PANEL_ADMIN'), ('TOKEN_API', 'TOKEN_API'), ('OTRO', 'OTRO')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Logs_AccionesUsuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('direccion_ip', models.CharField(max_length=40)),
                ('ruta', models.TextField(default='')),
                ('query', models.TextField(default='')),
                ('metodo_http', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE')], max_length=6)),
                ('estado_http', models.CharField(max_length=10)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Alarma_Programada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('id_paciente_ucr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teleasistenciaApp.paciente')),
                ('id_terminal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teleasistenciaApp.terminal')),
                ('id_tipo_alarma', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teleasistenciaApp.tipo_alarma')),
            ],
        ),
    ]
