# Generated by Django 3.2.3 on 2023-04-18 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teleasistenciaApp', '0019_alarma_programada_logs_accionesusuarios_logs_conexionesusuarios'),
    ]

    operations = [

        #migrations.RunSQL(
           # 'DELETE FROM teleasistenciaApp_persona_contacto_en_alarma WHERE ID >0'
        #),
        migrations.AlterField(
            model_name='persona_contacto_en_alarma',
            name='id_persona_contacto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teleasistenciaApp.relacion_paciente_persona'),
        ),
    ]
