# Generated by Django 3.2.3 on 2023-04-26 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teleasistenciaApp', '0021_database_database_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='relacion_paciente_persona',
            name='tiempo_domicilio',
            field=models.IntegerField(default=1),
        ),
    ]
