# Generated by Django 3.2.3 on 2023-05-08 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teleasistenciaApp', '0022_relacion_paciente_persona_tiempo_domicilio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desarrollador_tecnologia',
            name='id_tecnologia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teleasistenciaApp.tecnologia'),
        ),
    ]
