# Generated by Django 3.2.3 on 2023-05-16 07:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('teleasistenciaApp', '0023_alter_desarrollador_tecnologia_id_tecnologia'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminal',
            name='fecha_tipo_situacion',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='terminal',
            name='id_tipo_situacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teleasistenciaApp.tipo_situacion'),
        ),
        migrations.DeleteModel(
            name='Historico_Tipo_Situacion',
        ),
    ]
